[package]
name = "message_cache"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell    = "1.2"
parking_lot  = "0.10"
lru          = "0.4"

[dependencies.heraldcore]
path    = "../../heraldcore"
