DROP TABLE IF EXISTS chainkeys;
DROP TABLE IF EXISTS message_status;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS replies;
DROP TABLE IF EXISTS conversation_members;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS config;
DROP TABLE IF EXISTS conversations;
