DROP TABLE conversation_members;
DROP INDEX prekey_signer;
DROP TABLE prekeys;
DROP TABLE pending;
DROP INDEX push_ts_ix;
DROP TABLE pushes;
DROP TABLE sigchain;
DROP INDEX user_id_ix;
DROP TABLE userkeys;
