#!/usr/bin/env python3

import xml.etree.cElementTree as ET
from pathlib import Path
from os import listdir, renames
import sys

if len(sys.argv) != 4:
    print("Expected four arguments, found", len(sys.argv))
    print("Usage: ./qmv SOURCE DEST QRC_PATH")
    exit(1)

src, dest, qrc = sys.argv[1], sys.argv[2], sys.argv[3]

qrc = Path(qrc)
src = Path(src)
dest = Path(dest)

if not (src.exists()):
    print("%s not found" % src)

if not (qrc.exists()):
    print("No qrc file found at", qrc)
    exit(1)

with qrc.open() as f:
    root = ET.fromstring(f.read())

for file_name in root.iter("file"):
    file_name.text = file_name.text.replace(str(src), str(dest))

renames(src, dest)

with qrc.open("w") as f:
    out = ET.tostring(root, encoding="unicode")
    print(out)
    f.write(out)
