[tasks.start-postgres]
linux_alias = "start-postgres-linux"
mac_alis = "start-postgres-macos"

[tasks.start-postgres-linux]
command = "docker-compose"
args = ["up", "-d"]

[tasks.start-postgres-macos]
command = "docker-compose"
args = ["-f", "mac-docker-compose.yml", "up", "-d"]
