//! Client logic for herald.
#![deny(missing_docs)]
#![allow(clippy::all)]
#![macro_use]
extern crate heraldcore;

/// Implementation of autogenerated traits.
pub mod implementation;

/// Autogenerated by `rust-qt-binding-generator`.
#[allow(missing_docs)]
pub mod interface;

/// FFI type aliases.
pub mod ffi;
/// Shared state.
pub mod shared;
/// Desktop push notifications
pub mod toasts;
/// Utilities.
pub mod utils;
