//! Client logic for herald.
#![deny(missing_docs)]

/// Implementation of autogenerated traits.
#[allow(clippy::needless_return)]
pub mod imp;

/// Autogenerated by `rust-qt-binding-generator`.
#[allow(missing_docs)]
#[allow(clippy::all)]
#[allow(unused_parens)]
pub mod interface;

/// FFI type aliases.
pub mod ffi;
/// Shared state.
pub mod shared;
/// Desktop push notifications
pub mod toasts;
/// Utilities.
pub mod utils;

pub(crate) trait Loadable {
    type Error;

    fn try_load(&mut self) -> Result<(), Self::Error>;

    fn loaded(&self) -> bool;
}
