// this code was generated by the emoji_scraper.py script
extern crate arrayvec;
use arrayvec::ArrayVec;

Struct emoji_struct {{
    emoji: char
    tags: ArrayVec::<'static &str, 8>
}}

pub static [emoji_struct; {length} ]: emoji_data = {emoji_data}
